# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: 'CDSS Learn / Git'
pages:
- Introduction: index.md
- 'Lessons':
  - '1 - GitHub Account': '01-lesson-github-account/lesson-github-account.md'
  - '2 - Version Control Concepts': '02-lesson-concepts/lesson-concepts.md'
  - '3 - Install Git Software':
    - 'Overview': '03-lesson-install/overview.md'
    - 'Git': '03-lesson-install/git.md'
    - 'Eclipse EGit/JGit': '03-lesson-install/eclipse.md'
  - '4 - Configure Git': '04-lesson-config/lesson-config.md'
  - '5 - New Repository': '05-lesson-new-repo/lesson-new-repo.md'
  - '6 - Standard Repository Files': '06-lesson-standard-repo-files/lesson-standard-repo-files.md'
  - '7a - Using Git': '07a-lesson-using-git/lesson-using-git.md'
  - '7b - GitHub Tools': '07b-lesson-github-tools/lesson-github-tools.md'
  - '7c - Difference Tools': '07c-lesson-diff-tools/lesson-diff-tools.md'
  - '7d - Documentation Example': '07d-lesson-documentation-example/lesson-documentation-example.md'
  - '7e - StateMod Dataset Example': '07e-lesson-statemod-dataset-example/lesson-statemod-dataset-example.md'
  - '7f - StateMod Code Example': '07f-lesson-statemod-code-example/lesson-statemod-code-example.md'
  - '8a - Workflow Concepts': '08a-lesson-workflow-concepts/lesson-workflow-concepts.md'
  - '8b - Workflow Example for StateMod': '08b-lesson-workflow-example-statemod/lesson-workflow-example-statemod.md'
  - '9a - Merge Conflicts': '09a-lesson-merge-conflicts/lesson-merge-conflicts.md'
  - '10a - Pull Requests': '10a-lesson-pull-requests/lesson-pull-requests.md'
  - '11a - Editing History': '11a-lesson-editing-history/lesson-editing-history.md'
- 'Resources':
   - 'Git Resources': 'resources/resources.md'
   - 'Git Cheatsheet': 'resources/git-cheatsheet.md'
   - 'Git Glossary': 'resources/glossary.md'
   - 'Git Messages': 'resources/git-messages.md'
   - 'Git Bash (Shell)': 'resources/git-bash/git-bash.md'
   - 'Release Notes': 'resources/release-notes.md'
# MkDocs comes with mkdocs and readthedocs themes, which are limited
# Install material theme:  http://squidfunk.github.io/mkdocs-material/
# - pip install --user mkdocs-material
theme: material
#theme: readthedocs
# Don't include GitHub link because edit page tool will automatically be on
#repo_url:  https://github.com/OpenWaterFoundation/cdss-learn-git
site_description:  'CDSS / Learn Git'
site_author:  'OpenCDSS'
site_favicon:  'images/cdss-favicon.ico'
copyright:  'Copyright Colorado Department of Natural Resources'
# Extra options:
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
